use_frameworks!

platform :ios, '12.4'

install! 'cocoapods', :deterministic_uuids => false

target 'Sample' do
  pod 'Konnection', :path => '../../konnection'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end